package com.application.universum.account.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import lombok.*;

import java.io.Serializable;


@Entity
@AllArgsConstructor
@NoArgsConstructor
@Data
@Builder
@DynamoDBTable(tableName = "Account")
public class Account implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBRangeKey
    private String Name;
    // Refer to: https://www.baeldung.com/hibernate-notnull-vs-nullable
    //@Column(nullable = false)

    @DynamoDBRangeKey
    @NotBlank(message = "Email cannot be left empty")
    private String EmailAddress;

    @DynamoDBRangeKey
    private String Address;

    @DynamoDBRangeKey
    private int Age;

}
